name: Python Flask App Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Pin to Python 3.9, compatible with your dependencies

    - name: Install dependencies
      run: make install

    - name: Run Flask App (Sleep for 10 seconds to allow startup)
      run: |
        make run &
        sleep 10
        kill %1
